version: "3.8"
services:
  app_name-front:
    image: node:17-alpine
    container_name: app_name-front
    working_dir: /var/www/html/app/
    entrypoint: sh
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes: [ ./:/var/www/html/app ]
    tty: true
